/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hotel;
import javax.swing.JOptionPane;
import java.sql.*;
import java.text.SimpleDateFormat;

import project.*;
import java.util.Calendar;

/**
 *
 * @author abdullah
 */
public class CustomerCheckIn extends javax.swing.JFrame {

    /**
     * Creates new form CustomerCheckIn
     */
    public CustomerCheckIn() {
        initComponents();
        tcheckin.setEditable(false);
        tprice.setEditable(false);
        SimpleDateFormat myFormat = new SimpleDateFormat("yyyy-MM-dd");
        Calendar cal = Calendar.getInstance();
        tcheckin.setText(myFormat.format(cal.getTime()));
    }
    String roomNo;
    String bed;
    String roomType;
    String price;
    
    public void roomDetails(){
        troom.removeAllItems();
        tprice.setText("");
        bed = (String)tbed.getSelectedItem(); 
        roomType = (String)ac.getSelectedItem();

        try {
            ResultSet rs = Select.getData("select * from rooms where bed='" + bed + "' and roomType='" + roomType + "' and status='Not Booked'");
            while (rs.next()) {
                troom.addItem(rs.getString(1));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
            
        }     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        tcheckin = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        temail = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tprice = new javax.swing.JTextField();
        tbed = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        ac = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        troom = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        ballocate = new javax.swing.JButton();
        bclear = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(50, 118));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1266, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Email");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 350, -1));

        tcheckin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(tcheckin, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 130, 350, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Check IN Date (Today)");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 350, -1));

        temail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(temail, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 80, 350, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Bed");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 349, -1));

        tprice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(tprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 360, 351, -1));

        tbed.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tbed.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SINGLE", "DOUBLE", "TRIPPLE" }));
        tbed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbedActionPerformed(evt);
            }
        });
        getContentPane().add(tbed, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 200, 349, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Room Type");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 349, -1));

        ac.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ac.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "NON AC" }));
        ac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acActionPerformed(evt);
            }
        });
        getContentPane().add(ac, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 250, 350, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Room Number");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, 349, -1));

        troom.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        troom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                troomActionPerformed(evt);
            }
        });
        getContentPane().add(troom, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 310, 349, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Price");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, 349, -1));

        ballocate.setBackground(new java.awt.Color(153, 0, 51));
        ballocate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ballocate.setForeground(new java.awt.Color(255, 255, 255));
        ballocate.setText("Allocate Room");
        ballocate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ballocateActionPerformed(evt);
            }
        });
        getContentPane().add(ballocate, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 430, -1, -1));

        bclear.setBackground(new java.awt.Color(153, 0, 51));
        bclear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bclear.setForeground(new java.awt.Color(255, 255, 255));
        bclear.setText("Clear");
        bclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bclearActionPerformed(evt);
            }
        });
        getContentPane().add(bclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 430, 131, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 51));
        jLabel1.setText("Customer Check In");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 21, -1, -1));

        jButton1.setText("X");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 20, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tbedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbedActionPerformed
        // TODO add your handling code here:
       roomDetails();
    }//GEN-LAST:event_tbedActionPerformed

    private void acActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acActionPerformed
        // TODO add your handling code here:
        roomDetails();
    }//GEN-LAST:event_acActionPerformed

    private void troomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_troomActionPerformed
        // TODO add your handling code here:
        roomNo =(String)troom.getSelectedItem();
        try{
            ResultSet rs= Select.getData("select *from rooms where roomNo='"+roomNo+"'");
            while(rs.next()){
                tprice.setText(rs.getString(4));
            }

        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_troomActionPerformed

    private void ballocateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ballocateActionPerformed
        // TODO add your handling code here:
        int id = 1;
        String email = temail.getText(); // Fixed - was incorrectly using tcheckin
        String checkIn = tcheckin.getText(); // Fixed - was incorrectly using temail
        String bed = (String)tbed.getSelectedItem();
        String roomType = (String)ac.getSelectedItem();
        String roomNo = (String)troom.getSelectedItem();
        String price = tprice.getText();
        String Query = "select max(id) from customer";
        
        try {
            ResultSet rs = Select.getData(Query);
            while(rs.next()) {
                id = rs.getInt(1);
                id = id + 1;
            }

            if(!price.equals("")) {
                // Fixed table name from "room" to "rooms"
                Query = "update rooms set status='Booked' where roomno='" + roomNo + "'";
                InsertUpdateDelete.setData(Query, "");
                
                // Fixed INSERT query to match table structure
                Query = "insert into customer(id, email, checkIn, roomno, bed, roomType, price, numberOfDaysStay, totalAmount, checkOut) " + 
                       "values(" + id + ",'" + email + "','" + checkIn + "','" + roomNo + "','" + 
                       bed + "','" + roomType + "','" + price + "', 0, '0', 'Not Checked Out')";
                       
                InsertUpdateDelete.setData(Query, "Customer Check In Successfully");
                setVisible(false);
                new CustomerCheckIn().setVisible(true);
            }
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_ballocateActionPerformed

    private void bclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bclearActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new CustomerCheckIn().setVisible(true);
    }//GEN-LAST:event_bclearActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerCheckIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ac;
    private javax.swing.JButton ballocate;
    private javax.swing.JButton bclear;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> tbed;
    private javax.swing.JTextField tcheckin;
    private javax.swing.JTextField temail;
    private javax.swing.JTextField tprice;
    private javax.swing.JComboBox<String> troom;
    // End of variables declaration//GEN-END:variables
}
