/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hotel;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import project.*;
import java.awt.Desktop;

/**
 *
 * @author abdullah
 */
public class CustomerCheckOut extends javax.swing.JFrame {
    

    /**
     * Creates new form CustomerCheckOut
     */
    public CustomerCheckOut() {
        initComponents();
        tcheckin.setEditable(false);
        tday.setEditable(false);
        tamount.setEditable(false);
        tprice.setEditable(false);
    }
    int id = 0;
    String Query;
    String roomType;
    String bed;
    String roomNo;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        troom = new javax.swing.JTextField();
        search = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        tcheckin = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        temail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tprice = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tday = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tamount = new javax.swing.JTextField();
        checkout = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        tcheckout = new javax.swing.JTextField();

        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton5.setText("X");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 443));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1266, 500));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 51));
        jLabel1.setText("Customer Check Out");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 212, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Room Number");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 120, -1, -1));

        troom.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(troom, new org.netbeans.lib.awtextra.AbsoluteConstraints(404, 117, 85, -1));

        search.setBackground(new java.awt.Color(102, 0, 0));
        search.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        search.setForeground(new java.awt.Color(255, 255, 255));
        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        getContentPane().add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(577, 116, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Email");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(487, 188, -1, -1));

        tcheckin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(tcheckin, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 211, 250, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Check In Date");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 188, -1, -1));

        temail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(temail, new org.netbeans.lib.awtextra.AbsoluteConstraints(487, 211, 250, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Price Per Day");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 290, -1, -1));

        tprice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tpriceActionPerformed(evt);
            }
        });
        getContentPane().add(tprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 320, 250, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Number of Days Stay");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, -1, -1));

        tday.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(tday, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 250, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Total Amount to Collect From Customer");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 290, -1, -1));

        tamount.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(tamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 320, 250, -1));

        checkout.setBackground(new java.awt.Color(102, 0, 51));
        checkout.setForeground(new java.awt.Color(255, 255, 255));
        checkout.setText("Check Out");
        checkout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkoutActionPerformed(evt);
            }
        });
        getContentPane().add(checkout, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, -1, -1));

        clear.setBackground(new java.awt.Color(102, 0, 51));
        clear.setForeground(new java.awt.Color(255, 255, 255));
        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 390, -1, -1));

        jButton6.setText("X");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1183, 21, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Check Out Date (Today)");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(797, 188, -1, -1));
        getContentPane().add(tcheckout, new org.netbeans.lib.awtextra.AbsoluteConstraints(797, 212, 250, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
    // TODO add your handling code here:
    String roomNo = troom.getText();
    try {
        // Changed from "checkout is NULL" to "checkOut='Not Checked Out'"
        ResultSet rs = Select.getData("select * from customer where roomNo='" + roomNo + "' and checkOut='Not Checked Out'");
        if (rs.next()) {
            troom.setEditable(false);
            id = rs.getInt(1);
            temail.setText(rs.getString(2));     // Email field
            tcheckin.setText(rs.getString(3));   // CheckIn date field
            tprice.setText(rs.getString(7));     // Price field
            
            SimpleDateFormat myFormat = new SimpleDateFormat("yyyy-MM-dd");
            Calendar cal = Calendar.getInstance();
            tcheckout.setText(myFormat.format(cal.getTime()));
            
            String dateBeforeString = rs.getString(3);  // CheckIn date is in column 3
            java.util.Date datebefore = myFormat.parse(dateBeforeString); 
            String dateAfterString = myFormat.format(cal.getTime());
            java.util.Date dateAfter = myFormat.parse(dateAfterString);
            long difference = dateAfter.getTime() - datebefore.getTime();
            int noOfDayStay = (int) (difference / (1000 * 60 * 60 * 24));
            
            
            
            if (noOfDayStay == 0) {
                noOfDayStay = 1;
            }
            
            tday.setText(String.valueOf(noOfDayStay));
            float price = Float.parseFloat(tprice.getText());
            tamount.setText(String.valueOf(noOfDayStay * price));
            
            roomType = rs.getString(6);  // RoomType is in column 6
            bed = rs.getString(5);       // Bed is in column 5
            this.roomNo = roomNo; 
        } else {
            JOptionPane.showMessageDialog(null, "Room Number is not Booked or Room Number Does not Exist");
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
    }
}//GEN-LAST:event_searchActionPerformed

    private void checkoutActionPerformed(java.awt.event.ActionEvent evt) {
    // Get form data
    String email = temail.getText();
    String checkOut = tcheckout.getText();
    String numberOfDaysStay = tday.getText();
    String totalAmount = tamount.getText();
    roomNo = troom.getText();

    // Update database records
    Query = "update customer set numberOfDaysStay='" + numberOfDaysStay + "',totalAmount ='" + totalAmount + "', checkOut='" + checkOut + "' where id='" + id + "'";
    InsertUpdateDelete.setData(Query, "");
    Query = "update rooms set Status ='Not booked' where roomNo='" + roomNo + "'";
    InsertUpdateDelete.setData(Query, "");

    // Determine the path dynamically based on the operating system
    String path = System.getProperty("user.home") + File.separator + "Documents" + File.separator;
    com.itextpdf.text.Document doc = new com.itextpdf.text.Document();

     try {

            PdfWriter.getInstance(doc, new FileOutputStream(path + "" + id + ".pdf"));
            doc.open();
            Paragraph paragraph1 = new Paragraph("         HOTEL MANAGEMENT SYSTEM \\n       ");
            doc.add(paragraph1);
            Paragraph paragraph2 = new Paragraph("*********************************************************************************************\\n       ");

            doc.add(paragraph2);

            Paragraph paragraph3 = new Paragraph("\tBill ID: " + id + "\nCustomer Deatils:\n" + "\nEmail: " + email + "\n");

            doc.add(paragraph3);

            doc.add(paragraph2);

            Paragraph paragraph4 = new Paragraph("\tRoom Details:\nNumber: " + troom.getText() + "\nType: " + roomType + "\nBed: " + bed + "\nPrice Per Day: " +  tprice.getText() + " ");
            doc.add(paragraph4);

            doc.add(paragraph2);

            PdfPTable tb1 = new PdfPTable(4);
            tb1.addCell("Check IN Date: " + tcheckin.getText());
            tb1.addCell("Check Out Date: " + tcheckout.getText());
            tb1.addCell("No of Days Stay: " + numberOfDaysStay);
            tb1.addCell("Total Amount Paid: " + totalAmount);
            doc.add(tb1);
            doc.add(paragraph2);

            Paragraph paragraph5 = new Paragraph("    Thank you, Please Visit Again.      ");
            doc.add(paragraph5);

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, e);

        }

        doc.close();
        int a = JOptionPane.showConfirmDialog(null, "Do you want to Print Bill?", "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            try {
                File pdfFile = new File(path + id + ".pdf");
                if (pdfFile.exists()) {
                    if (Desktop.isDesktopSupported()) {
                        Desktop.getDesktop().open(pdfFile);
                    } else {
                        JOptionPane.showMessageDialog(null, "Desktop is not supported on this system.");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "File does not exist.");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error while opening PDF: " + e.getMessage());
            }
        }
        setVisible(false);
        new CustomerCheckOut().setVisible(true);
}

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new CustomerCheckOut().setVisible(true);

    }//GEN-LAST:event_clearActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void tpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tpriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tpriceActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        // Change the query to check for "Not Checked Out" instead of NULL
       
    }//GEN-LAST:event_formComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerCheckOut().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton checkout;
    private javax.swing.JButton clear;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton search;
    private javax.swing.JTextField tamount;
    private javax.swing.JTextField tcheckin;
    private javax.swing.JTextField tcheckout;
    private javax.swing.JTextField tday;
    private javax.swing.JTextField temail;
    private javax.swing.JTextField tprice;
    private javax.swing.JTextField troom;
    // End of variables declaration//GEN-END:variables
}
