/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hotel;
import java.sql.*;

import javax.swing.JOptionPane;

import project.*;

/**
 *
 * @author abdullah
 */
public class forgot_passowrd extends javax.swing.JFrame {

    /**
     * Creates new form forgot_passowrd
     */
    public forgot_passowrd() {
        initComponents();
    }
    
    String email;

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        temail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        search = new javax.swing.JButton();
        tphone = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tpass = new javax.swing.JTextField();
        save = new javax.swing.JButton();
        ID = new javax.swing.JLabel();
        tid = new javax.swing.JTextField();
        login = new javax.swing.JButton();
        reg = new javax.swing.JButton();
        tclose = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1400, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Forgot password ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(498, 141, -1, -1));
        getContentPane().add(temail, new org.netbeans.lib.awtextra.AbsoluteConstraints(522, 258, 418, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Email");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 260, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Phone number");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 381, -1, -1));

        search.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        getContentPane().add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(1106, 257, -1, -1));
        getContentPane().add(tphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(522, 379, 418, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("New Password");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 441, -1, -1));
        getContentPane().add(tpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(522, 439, 418, -1));

        save.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(588, 541, -1, -1));

        ID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ID.setText("ID");
        getContentPane().add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 319, -1, -1));
        getContentPane().add(tid, new org.netbeans.lib.awtextra.AbsoluteConstraints(522, 321, 418, -1));

        login.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        login.setText("login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        getContentPane().add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 541, -1, -1));

        reg.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        reg.setText("registration");
        reg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regActionPerformed(evt);
            }
        });
        getContentPane().add(reg, new org.netbeans.lib.awtextra.AbsoluteConstraints(817, 541, -1, -1));

        tclose.setBackground(new java.awt.Color(204, 0, 51));
        tclose.setForeground(new java.awt.Color(255, 255, 255));
        tclose.setText("X");
        tclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tcloseActionPerformed(evt);
            }
        });
        getContentPane().add(tclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 21, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        int check = 0;
        email = temail.getText();
        if (email.equals("")) {
            check = 1;
            JOptionPane.showMessageDialog(null, "Please enter your email");
        } else {
            ResultSet rs = Select.getData("select * from users where email = '" + email + "'");
            try {
                if (rs.next()) {
                    check = 1;
                    tid.setEditable(false);
                    temail.setEditable(false);
                    tid.setText(rs.getString(7));
                } else {
                    check = 0;
                    JOptionPane.showMessageDialog(null, "Email not found");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }

            if (check == 0) {
                JOptionPane.showMessageDialog(null, "Email not found");
            }
            
        }
        
    }//GEN-LAST:event_searchActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        int check = 0;
        String id = tid.getText();
        String phone = tphone.getText();
        String newpass = tpass.getText();

        if (phone.equals("") || newpass.equals("")) {
            check = 1;
            JOptionPane.showMessageDialog(null, "Please fill all fields");
        } else {
            ResultSet rs = Select.getData("select * from users where email = '" + email + "'  and id = '" + id + "'and phone = '" + phone + "'");   
            try {
                if (rs.next()) {
                    check = 1;
                    InsertUpdateDelete.setData("update users set password = '" + newpass + "' where email = '" + email + "'", "Password updated successfully");
                    setVisible(false);
                    new forgot_passowrd().setVisible(true);
                } else {
                    check = 0;
                    JOptionPane.showMessageDialog(null, "Incorrect phone number");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }

            if (check == 0) {
                JOptionPane.showMessageDialog(null, "Incorrect phone number");
            }
            
        }
    }//GEN-LAST:event_saveActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // Open the login page and close the current sign up page
        setVisible(false);
        new login().setVisible(true);
    }//GEN-LAST:event_loginActionPerformed

    private void regActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new sign_up().setVisible(true);
    }//GEN-LAST:event_regActionPerformed

    private void tcloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tcloseActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Do you want to close the application?", "Select", JOptionPane.YES_NO_OPTION);
        if(a == 0)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_tcloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(forgot_passowrd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(forgot_passowrd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(forgot_passowrd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(forgot_passowrd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new forgot_passowrd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ID;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton login;
    private javax.swing.JButton reg;
    private javax.swing.JButton save;
    private javax.swing.JButton search;
    private javax.swing.JButton tclose;
    private javax.swing.JTextField temail;
    private javax.swing.JTextField tid;
    private javax.swing.JTextField tpass;
    private javax.swing.JTextField tphone;
    // End of variables declaration//GEN-END:variables
}
