/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hotel;

import java.sql.*;
import javax.swing.JOptionPane;
import hotel.adminHome;
import project.Select;

/**
 *
 * @author abdullah
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        tpassword = new javax.swing.JPasswordField();
        tclose = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        temail = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tpassword1 = new javax.swing.JPasswordField();
        login = new javax.swing.JButton();
        reg = new javax.swing.JButton();
        forgot = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jLabel9.setText("Password");

        tclose.setText("X");
        tclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tcloseActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 25, 1400, 600));
        setMaximumSize(new java.awt.Dimension(16000, 9000));
        setMinimumSize(new java.awt.Dimension(1000, 500));
        setPreferredSize(new java.awt.Dimension(1600, 813));
        setSize(new java.awt.Dimension(1600, 813));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Email");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 270, -1, -1));

        temail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                temailFocusLost(evt);
            }
        });
        temail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temailActionPerformed(evt);
            }
        });
        getContentPane().add(temail, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 260, 423, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Password");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 340, -1, 30));
        getContentPane().add(tpassword1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 340, 423, 30));

        login.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        login.setText("login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        getContentPane().add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 450, -1, -1));

        reg.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        reg.setText("registration");
        reg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regActionPerformed(evt);
            }
        });
        getContentPane().add(reg, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 530, -1, -1));

        forgot.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        forgot.setText("Forgot password");
        forgot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forgotActionPerformed(evt);
            }
        });
        getContentPane().add(forgot, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 530, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Sign In");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 130, 111, 37));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/1.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void temailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_temailFocusLost
        // TODO add your handling code here:
        String regex = "^[a-zA-Z0-9+_.-]+@[a-zA-Z0-9.-]+$";
        String em = temail.getText();
        boolean result = em.matches(regex);
        if(!em.isBlank() && !result)
        {
            JOptionPane.showMessageDialog(temail,"Email is not valid. Please enter a correct email address.");
        }
    }//GEN-LAST:event_temailFocusLost

    private void temailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_temailActionPerformed

    private void tcloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tcloseActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Do you want to close the application?", "Select", JOptionPane.YES_NO_OPTION);
        if(a == 0)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_tcloseActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
    // TODO add your handling code here:
    int check = 0;
    String email = temail.getText();
    String password = tpassword1.getText();
    if(email.equals("")|| password.equals(""))
    {
        check = 1;
        JOptionPane.showMessageDialog(null, "Every Filed Is Required");
    }
    else if(email.equals("admin") && password.equals("admin"))
    {
        check = 1;
        setVisible(false);
        new adminHome().setVisible(true);            
    }
    else
    {
        ResultSet rs = Select.getData("select * from users where email='"+email+"' and password='"+password+"'");
        try {
            if(rs.next())
            {
                check = 1;
                if (rs.getString(9).equals("false"))
                {
                    setVisible(false);
                    // Check user role and redirect accordingly
                    String userRole = rs.getString(6); // Assuming 'role' column exists in users table
                    if(userRole != null && userRole.equalsIgnoreCase("manager")) {
                        // If user is a manager, navigate to Manager page
                        new Manager().setVisible(true);
                    } else if(userRole != null && userRole.equalsIgnoreCase("Technical Staff")) {
                        // If user is technical staff, navigate to Technical Staff page
                        new technical_staff().setVisible(true);
                    } else {
                        // For regular users
                        new Home().setVisible(true);
                    }
                } 
                else 
                {
                    JOptionPane.showMessageDialog(null,"wait for admin approval");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        if(check == 0)
        {
            JOptionPane.showMessageDialog(null, "Incorrect email or password");
        }
    }
}//GEN-LAST:event_loginActionPerformed

    private void regActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new sign_up().setVisible(true);
    }//GEN-LAST:event_regActionPerformed

    private void forgotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forgotActionPerformed
    // Navigate to the forgot password page
    setVisible(false);
    new forgot_passowrd().setVisible(true);
}//GEN-LAST:event_forgotActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton forgot;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton login;
    private javax.swing.JButton reg;
    private javax.swing.JButton tclose;
    private javax.swing.JTextField temail;
    private javax.swing.JPasswordField tpassword;
    private javax.swing.JPasswordField tpassword1;
    // End of variables declaration//GEN-END:variables
}
