/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hotel;
import project.*;
import java.sql.*;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


import project.InsertUpdateDelete;

/**
 *
 * @author abdullah
 */
public class ManageRoom extends javax.swing.JFrame {

    /**
     * Creates new form ManageRoom
     */
    public ManageRoom() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        troom = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ac = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        tbed = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        tprice = new javax.swing.JTextField();
        add = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1128, 640));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 51));
        jLabel1.setText("Manage Room");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 15, 163, -1));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Room Number", "Room Type", "Bed", "Price", "Status"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 100, 494, 480));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Room Number");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(581, 100, -1, -1));

        troom.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(troom, new org.netbeans.lib.awtextra.AbsoluteConstraints(581, 145, 447, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Room Type");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(581, 212, -1, -1));

        ac.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ac.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "NON AC", " " }));
        ac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acActionPerformed(evt);
            }
        });
        getContentPane().add(ac, new org.netbeans.lib.awtextra.AbsoluteConstraints(581, 256, 447, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Bed");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(581, 325, -1, -1));

        tbed.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tbed.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SINGLE", "DOUBLE", "TRIPPLE" }));
        getContentPane().add(tbed, new org.netbeans.lib.awtextra.AbsoluteConstraints(581, 372, 447, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Price");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(581, 435, -1, -1));

        tprice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(tprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(581, 484, 447, -1));

        add.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        add.setForeground(new java.awt.Color(102, 0, 51));
        add.setText("Add Room");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        getContentPane().add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(607, 557, -1, -1));

        jButton2.setText("X");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1057, 24, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void acActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // Get values from form fields
        String roomNo = troom.getText();
        String roomType = (String)ac.getSelectedItem();
        String bed = (String)tbed.getSelectedItem();
        String price = tprice.getText();
        
        // Validate input fields
        if(roomNo.isEmpty() || price.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Room number and price cannot be empty");
            return;
        }

        // Fixed SQL query to use the extracted values instead of component references
        String Query = "insert into rooms values('" + roomNo + "','" + roomType + "','" + bed + "','" + price + "','Not Booked')";
        InsertUpdateDelete.setData(Query, "Room Added Successfully");
        setVisible(false);
        new ManageRoom().setVisible(true);
    }//GEN-LAST:event_addActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // Clear existing table data to prevent duplicates when refreshing
        DefaultTableModel model = (DefaultTableModel)table.getModel();
        model.setRowCount(0);
        
        // Get data from database
        ResultSet rs = Select.getData("select * from rooms");
        try {
            while (rs.next()) {
                model.addRow(new Object[]{rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5)});
            }
            rs.close();
        } catch (Exception e) {
            // Fixed error message to show actual exception
            JOptionPane.showMessageDialog(null, e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_formComponentShown

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        // Get selected row
        int row = table.getSelectedRow();
        if (row >= 0) {
            // Get room number and current status
            String roomNumber = table.getValueAt(row, 0).toString();
            String currentStatus = table.getValueAt(row, 4).toString();
            
            // Determine new status
            String newStatus = currentStatus.equals("Booked") ? "Not Booked" : "Booked";
            
            // Show confirmation dialog
            int confirm = JOptionPane.showConfirmDialog(null, 
                    "Do you want to change the status of Room " + roomNumber + 
                    " from '" + currentStatus + "' to '" + newStatus + "'?", 
                    "Change Room Status", 
                    JOptionPane.YES_NO_OPTION);
            
            // If confirmed, update status
            if (confirm == JOptionPane.YES_OPTION) {
                try {
                    // Update database
                    String query = "UPDATE rooms SET status = '" + newStatus + 
                            "' WHERE roomNo = '" + roomNumber + "'";
                    InsertUpdateDelete.setData(query, "Room status updated successfully");
                    
                    // Update table display
                    table.setValueAt(newStatus, row, 4);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e.getMessage());
                }
            }
        }
    }//GEN-LAST:event_tableMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageRoom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ac;
    private javax.swing.JButton add;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    private javax.swing.JComboBox<String> tbed;
    private javax.swing.JTextField tprice;
    private javax.swing.JTextField troom;
    // End of variables declaration//GEN-END:variables
}
