/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hotel;

import javax.swing.JOptionPane;

import project.InsertUpdateDelete;

/**
 *
 * @author abdullah
 */
public class sign_up extends javax.swing.JFrame {

    /**
     * Creates new form sign_up
     */
    public sign_up() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tadd = new javax.swing.JTextField();
        textcid = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        temail = new javax.swing.JTextField();
        tname = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        rmale = new javax.swing.JRadioButton();
        tphone = new javax.swing.JTextField();
        rfemale = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tpassword = new javax.swing.JPasswordField();
        cmbdis = new javax.swing.JComboBox<>();
        reg = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        login = new javax.swing.JButton();
        tclose = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1600, 813));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Phone");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 300, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText(" Id ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 550, -1, 20));
        getContentPane().add(tadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 230, 389, -1));

        textcid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textcidActionPerformed(evt);
            }
        });
        getContentPane().add(textcid, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 550, 376, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Gender");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 420, -1, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, -1, -1));

        temail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                temailFocusLost(evt);
            }
        });
        temail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temailActionPerformed(evt);
            }
        });
        getContentPane().add(temail, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 350, 389, 30));

        tname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tnameFocusLost(evt);
            }
        });
        tname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnameActionPerformed(evt);
            }
        });
        getContentPane().add(tname, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 180, 389, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Email");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 350, -1, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Address");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, -1, -1));

        rmale.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rmale);
        rmale.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rmale.setText("Male");
        getContentPane().add(rmale, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 420, -1, 30));
        getContentPane().add(tphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 290, 389, -1));

        rfemale.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rfemale);
        rfemale.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rfemale.setText("Female");
        getContentPane().add(rfemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 420, -1, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Password");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 620, -1, 20));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Person");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 490, -1, 20));
        getContentPane().add(tpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 620, 376, 30));

        cmbdis.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmbdis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Guest", "Manager", "Technical Staff", "Housekeeper", "Service Provider" }));
        cmbdis.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cmbdis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbdisActionPerformed(evt);
            }
        });
        getContentPane().add(cmbdis, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 490, 285, 30));

        reg.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        reg.setText("registration");
        reg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regActionPerformed(evt);
            }
        });
        getContentPane().add(reg, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 720, -1, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Sign Up");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 80, -1, -1));

        login.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        login.setText("login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        getContentPane().add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 40, -1, -1));

        tclose.setBackground(new java.awt.Color(204, 0, 51));
        tclose.setForeground(new java.awt.Color(255, 255, 255));
        tclose.setText("X");
        tclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tcloseActionPerformed(evt);
            }
        });
        getContentPane().add(tclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 32, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/1.png"))); // NOI18N
        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textcidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textcidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textcidActionPerformed

    private void temailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_temailFocusLost
        // TODO add your handling code here:
        String regex = "^[a-zA-Z0-9+_.-]+@[a-zA-Z0-9.-]+$";
        String em = temail.getText();
        boolean result = em.matches(regex);
        if(!em.isBlank() && !result)
        {
            JOptionPane.showMessageDialog(temail,"Email is not valid. Please enter a correct email address.");
        }
    }//GEN-LAST:event_temailFocusLost

    private void temailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_temailActionPerformed

    private void tnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tnameFocusLost

        String name = tname.getText().trim();
        if(name.isBlank()){
            //Jmsg.setText("Name can't be null");
            JOptionPane.showMessageDialog(tname, "Name can't be null");
            JOptionPane.showMessageDialog(tname,"Name field cannot be empty. Please enter your name.");
            tname.grabFocus();
        }
    }//GEN-LAST:event_tnameFocusLost

    private void tnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tnameActionPerformed

    private void cmbdisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbdisActionPerformed
        // Generate 6-digit ID based on selected category
        String selectedPerson = cmbdis.getSelectedItem().toString();
        String prefix = "";

        // Set prefix based on person category
        switch(selectedPerson) {
            case "Guest":
            prefix = "10";
            break;
            case "Manager":
            prefix = "20";
            break;
            case "Technical Staff":
            prefix = "30";
            break;
            case "Housekeeper":
            prefix = "40";
            break;
            case "Service Provider":
            prefix = "50";
            break;
        }

        // Generate random 4 digits to complete the 6-digit ID
        int random = (int) (Math.random() * 10000);
        String randomStr = String.format("%04d", random); // Ensure 4 digits with leading zeros

        // Set the ID in the textcid field
        textcid.setText(prefix + randomStr);
    }//GEN-LAST:event_cmbdisActionPerformed

    private void regActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regActionPerformed
        // TODO add your handling code here:
        String name = tname.getText();
        String add = tadd.getText();
        String phone = tphone.getText();
        String email = temail.getText();
        String gender = rmale.isSelected() ? "Male" : "Female";
        String personType = cmbdis.getSelectedItem().toString();
        String id = textcid.getText();
        String password = new String(tpassword.getPassword());
        
        if(name.isEmpty() || add.isEmpty() || phone.isEmpty() || email.isEmpty() || id.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please fill all fields");
        }
        else
        {
            String Query;
            Query = "insert into users(name, address, phone, email, gender, person, id, password, status) values('" + name + "','" + add + "','" + phone + "','" + email + "','" + gender + "','" + personType + "','" + id + "','" + password + "','false')";
            InsertUpdateDelete.setData(Query, "Registration successful");
            setVisible(false);
            new sign_up().setVisible(true);
        }
        
    }//GEN-LAST:event_regActionPerformed

    private void tcloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tcloseActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Do you want to close the application?", "Select", JOptionPane.YES_NO_OPTION);
        if(a == 0)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_tcloseActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // Open the login page and close the current sign up page
        setVisible(false);
        new login().setVisible(true);
    }//GEN-LAST:event_loginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sign_up().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmbdis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton login;
    private javax.swing.JButton reg;
    private javax.swing.JRadioButton rfemale;
    private javax.swing.JRadioButton rmale;
    private javax.swing.JTextField tadd;
    private javax.swing.JButton tclose;
    private javax.swing.JTextField temail;
    private javax.swing.JTextField textcid;
    private javax.swing.JTextField tname;
    private javax.swing.JPasswordField tpassword;
    private javax.swing.JTextField tphone;
    // End of variables declaration//GEN-END:variables
}
